// <auto-generated />
using System;
using GhostWriter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GhostWriter.Infrastructure.Migrations
{
    [DbContext(typeof(Entities))]
    [Migration("20210720092249_disputePaymentToAuthorColumn")]
    partial class disputePaymentToAuthorColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BuzzwordProject", b =>
                {
                    b.Property<int>("BuzzwordsId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.HasKey("BuzzwordsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("BuzzwordProject");
                });

            modelBuilder.Entity("BuzzwordUserRoleData", b =>
                {
                    b.Property<int>("BuzzwordsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserRoleDatasId")
                        .HasColumnType("integer");

                    b.HasKey("BuzzwordsId", "UserRoleDatasId");

                    b.HasIndex("UserRoleDatasId");

                    b.ToTable("BuzzwordUserRoleData");
                });

            modelBuilder.Entity("ExpertiseAreaProject", b =>
                {
                    b.Property<int>("ExpertiseAreasId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.HasKey("ExpertiseAreasId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("ExpertiseAreaProject");
                });

            modelBuilder.Entity("ExpertiseAreaUserRoleData", b =>
                {
                    b.Property<int>("ExpertiseAreasId")
                        .HasColumnType("integer");

                    b.Property<int>("UserRoleDatasId")
                        .HasColumnType("integer");

                    b.HasKey("ExpertiseAreasId", "UserRoleDatasId");

                    b.HasIndex("UserRoleDatasId");

                    b.ToTable("ExpertiseAreaUserRoleData");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "28f61427-ef67-4a28-bb35-496775585c93",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "c8d91a1b-0d63-438e-bc12-c4d9c3106948",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "5afc6b0a-c9eb-4158-9522-a2160daada34",
                            Name = "Ghostwriter",
                            NormalizedName = "GHOSTWRITER"
                        });
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b9e96d3b-fc25-418b-91fb-bc997373ec78",
                            DateCreated = new DateTime(2021, 7, 20, 9, 22, 48, 115, DateTimeKind.Utc).AddTicks(2808),
                            Email = "aleksandar_stojcic@code3profit.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEKSANDAR_STOJCIC@CODE3PROFIT.COM",
                            NormalizedUserName = "ALEKSANDAR_STOJCIC@CODE3PROFIT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEG7/tSaiCBzkF0wGCkztUpBYJYzUxeHDvK6Tg0U1F7GMsFV2Is9D8UhlkZ44fx/zpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10627e8a-713c-4dcd-ab97-f445adf192c2",
                            TwoFactorEnabled = false,
                            UserName = "aleksandar_stojcic@code3profit.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66fdd4a8-5a6f-4870-ae48-f8d3e3332485",
                            DateCreated = new DateTime(2021, 7, 20, 9, 22, 48, 116, DateTimeKind.Utc).AddTicks(9286),
                            Email = "dasa_manic@code3profit.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DASA_MANIC@CODE3PROFIT.COM",
                            NormalizedUserName = "DASA_MANIC@CODE3PROFIT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKXLN/ByrTexwi1uh13NsvoBXhedcSDeyAfJPNo9whxINJPZFF5Gnpv2Fb2d8d/+Tg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96c17f26-e949-4ee3-8a4f-2c7d946e1c4e",
                            TwoFactorEnabled = false,
                            UserName = "dasa_manic@code3profit.com"
                        });
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserRoleDataId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserRoleDataId")
                        .IsUnique();

                    b.ToTable("ApplicationUserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GHWReceivedConfirmation")
                        .HasColumnType("boolean");

                    b.Property<int?>("HeadProposalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<bool>("PlagueScanned")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalServiceCharges")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HeadProposalId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingStatusHistory");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Buzzword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buzzword");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BinaryDocumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HeadProposalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BinaryDocumentId");

                    b.HasIndex("HeadProposalId")
                        .IsUnique();

                    b.ToTable("Conversation");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Degree");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Description = "Kein Abschluss/Nicht festgelegt",
                            Stage = 1,
                            Value = "Kein Abschluss/Nicht festgelegt"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hausarbeit",
                            Stage = 1,
                            Value = "Hausarbeit"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kirchlicher Abschluss",
                            Stage = 1,
                            Value = "Kirchlicher Abschluss"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bachelor of Arts (B.A.)",
                            Stage = 2,
                            Value = "Bachelor of Arts (B.A.)"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bachelor of Engineering (B.Eng.)",
                            Stage = 2,
                            Value = "Bachelor of Engineering (B.Eng.)"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bachelor of Education (B.Ed.)",
                            Stage = 2,
                            Value = "Bachelor of Education (B.Ed.)"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bachelor of Science (B.Sc.)",
                            Stage = 2,
                            Value = "Bachelor of Science (B.Sc.)"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Bachelor of Laws (LL.B.)",
                            Stage = 2,
                            Value = "Bachelor of Laws (LL.B.)"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Bachelor of Science in Information Technology (B.Sc.IT)",
                            Stage = 2,
                            Value = "Bachelor of Science in Information Technology (B.Sc.IT)"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Bachelor sonstiges",
                            Stage = 2,
                            Value = "Bachelor sonstiges"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Diplom (Uni)",
                            Stage = 2,
                            Value = "Diplom (Uni)"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Diplom (FH)",
                            Stage = 2,
                            Value = "Diplom (FH)"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Master of Engineering (M.Eng.)",
                            Stage = 3,
                            Value = "Master of Engineering (M.Eng.)"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Master of Education (M.Ed.)",
                            Stage = 3,
                            Value = "Master of Education (M.Ed.)"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Master of Science (M.Sc.)",
                            Stage = 3,
                            Value = "Master of Science (M.Sc.)"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Master of Laws (LL.M.)",
                            Stage = 3,
                            Value = "Master of Laws (LL.M.)"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Master of Business Administration (MBA)",
                            Stage = 3,
                            Value = "Master of Business Administration (MBA)"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Habilitation",
                            Stage = 4,
                            Value = "Habilitation"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Dr.",
                            Stage = 4,
                            Value = "Dr."
                        },
                        new
                        {
                            Id = 22,
                            Description = "Prof.",
                            Stage = 4,
                            Value = "Prof."
                        },
                        new
                        {
                            Id = 23,
                            Description = "Magister",
                            Stage = 4,
                            Value = "Magister"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Fakultätsexamen",
                            Stage = 1,
                            Value = "Fakultätsexamen"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Master of Arts (M.A.)",
                            Stage = 3,
                            Value = "Master of Arts (M.A.)"
                        });
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Dispute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateClosed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DisputeStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaymentToAuthor")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Dispute");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<string>("CopyLeaksScanId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("FileBinary")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsFinalVersion")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<string>("PrivateName")
                        .HasColumnType("text");

                    b.Property<string>("PublicName")
                        .HasColumnType("text");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ExpertiseArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FieldStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExpertiseArea");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Description = "Erziehungswissenschaften/Pädagogik",
                            FieldStatus = 1,
                            Value = "Erziehungswissenschaften/Pädagogik"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Politikwissenschaft",
                            FieldStatus = 1,
                            Value = "Politikwissenschaft"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Psychologie",
                            FieldStatus = 1,
                            Value = "Psychologie"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Wirtschaftspsychologie",
                            FieldStatus = 1,
                            Value = "Wirtschaftspsychologie"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Soziologie",
                            FieldStatus = 1,
                            Value = "Soziologie"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Sport",
                            FieldStatus = 1,
                            Value = "Sport"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Theologie",
                            FieldStatus = 1,
                            Value = "Theologie"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Bibliothekswesen",
                            FieldStatus = 1,
                            Value = "Bibliothekswesen"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Design",
                            FieldStatus = 1,
                            Value = "Design"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Germanistik",
                            FieldStatus = 1,
                            Value = "Germanistik"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Geschichte",
                            FieldStatus = 1,
                            Value = "Geschichte"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Gestaltung",
                            FieldStatus = 1,
                            Value = "Gestaltung"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Architektur",
                            FieldStatus = 1,
                            Value = "Architektur"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Journalismus",
                            FieldStatus = 1,
                            Value = "Journalismus"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Kommunikationswissenschaft",
                            FieldStatus = 1,
                            Value = "Kommunikationswissenschaft"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Kulturwissenschaft",
                            FieldStatus = 1,
                            Value = "Kulturwissenschaft"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Kunstgeschichte",
                            FieldStatus = 1,
                            Value = "Kunstgeschichte"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Medienwissenschaft",
                            FieldStatus = 1,
                            Value = "Medienwissenschaft"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Musik",
                            FieldStatus = 1,
                            Value = "Musik"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Philologie",
                            FieldStatus = 1,
                            Value = "Philologie"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Philosophie",
                            FieldStatus = 1,
                            Value = "Philosophie"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Publizistik",
                            FieldStatus = 1,
                            Value = "Publizistik"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Religion",
                            FieldStatus = 1,
                            Value = "Religion"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Sprachwissenschaften",
                            FieldStatus = 1,
                            Value = "Sprachwissenschaften"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Theaterwissenschaft",
                            FieldStatus = 1,
                            Value = "Theaterwissenschaft"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Biochemie",
                            FieldStatus = 1,
                            Value = "Biochemie"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Biologie",
                            FieldStatus = 1,
                            Value = "Biologie"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Chemie",
                            FieldStatus = 1,
                            Value = "Chemie"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Ernährungswissenschaften",
                            FieldStatus = 1,
                            Value = "Ernährungswissenschaften"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Geografie",
                            FieldStatus = 1,
                            Value = "Geografie"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Geologie",
                            FieldStatus = 1,
                            Value = "Geologie"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Physik",
                            FieldStatus = 1,
                            Value = "Physik"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Statistik",
                            FieldStatus = 1,
                            Value = "Statistik"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Mathematik",
                            FieldStatus = 1,
                            Value = "Mathematik"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Verfahrenstechnik",
                            FieldStatus = 1,
                            Value = "Verfahrenstechnik"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Informatik",
                            FieldStatus = 1,
                            Value = "Informatik"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Haushalt",
                            FieldStatus = 1,
                            Value = "Haushalt"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Medizin",
                            FieldStatus = 1,
                            Value = "Medizin"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Gesundheitswissenschaften",
                            FieldStatus = 1,
                            Value = "Gesundheitswissenschaften"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Pharmazie",
                            FieldStatus = 1,
                            Value = "Pharmazie"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Pharmatechnik",
                            FieldStatus = 1,
                            Value = "Pharmatechnik"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Zahnmedizin",
                            FieldStatus = 1,
                            Value = "Zahnmedizin"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Tiermedizin",
                            FieldStatus = 1,
                            Value = "Tiermedizin"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Agrarwissenschaft",
                            FieldStatus = 1,
                            Value = "Agrarwissenschaft"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Forstwissenschaft",
                            FieldStatus = 1,
                            Value = "Forstwissenschaft"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Gartenbau",
                            FieldStatus = 1,
                            Value = "Gartenbau"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Holzwirtschaft",
                            FieldStatus = 1,
                            Value = "Holzwirtschaft"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Holztechnik",
                            FieldStatus = 1,
                            Value = "Holztechnik"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Landschaftsarchitektur",
                            FieldStatus = 1,
                            Value = "Landschaftsarchitektur"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Landwirtschaft",
                            FieldStatus = 1,
                            Value = "Landwirtschaft"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Betriebswirtschaft",
                            FieldStatus = 1,
                            Value = "Betriebswirtschaft"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Volkswirtschaft",
                            FieldStatus = 1,
                            Value = "Volkswirtschaft"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Wirtschaftspädagogik",
                            FieldStatus = 1,
                            Value = "Wirtschaftspädagogik"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Bauingenieurwesen",
                            FieldStatus = 1,
                            Value = "Bauingenieurwesen"
                        },
                        new
                        {
                            Id = 106,
                            Description = "Drucktechnik",
                            FieldStatus = 1,
                            Value = "Drucktechnik"
                        },
                        new
                        {
                            Id = 107,
                            Description = "Elektrotechnik",
                            FieldStatus = 1,
                            Value = "Elektrotechnik"
                        },
                        new
                        {
                            Id = 108,
                            Description = "Informationstechnik",
                            FieldStatus = 1,
                            Value = "Informationstechnik"
                        },
                        new
                        {
                            Id = 109,
                            Description = "Lebensmitteltechnologie",
                            FieldStatus = 1,
                            Value = "Lebensmitteltechnologie"
                        },
                        new
                        {
                            Id = 110,
                            Description = "Maschinenbau",
                            FieldStatus = 1,
                            Value = "Maschinenbau"
                        },
                        new
                        {
                            Id = 111,
                            Description = "Medientechnik",
                            FieldStatus = 1,
                            Value = "Medientechnik"
                        },
                        new
                        {
                            Id = 112,
                            Description = "Raumplanung",
                            FieldStatus = 1,
                            Value = "Raumplanung"
                        },
                        new
                        {
                            Id = 113,
                            Description = "Umweltschutz",
                            FieldStatus = 1,
                            Value = "Umweltschutz"
                        },
                        new
                        {
                            Id = 114,
                            Description = "Vermessungswesen",
                            FieldStatus = 1,
                            Value = "Vermessungswesen"
                        },
                        new
                        {
                            Id = 115,
                            Description = "Materialwissenschaften",
                            FieldStatus = 1,
                            Value = "Materialwissenschaften"
                        },
                        new
                        {
                            Id = 116,
                            Description = "Jura",
                            FieldStatus = 1,
                            Value = "Jura"
                        },
                        new
                        {
                            Id = 117,
                            Description = "Medienrecht",
                            FieldStatus = 1,
                            Value = "Medienrecht"
                        },
                        new
                        {
                            Id = 118,
                            Description = "Wirtschaftsrecht",
                            FieldStatus = 1,
                            Value = "Wirtschaftsrecht"
                        },
                        new
                        {
                            Id = 119,
                            Description = "Strafrecht",
                            FieldStatus = 1,
                            Value = "Strafrecht"
                        },
                        new
                        {
                            Id = 120,
                            Description = "Datenschutzrecht",
                            FieldStatus = 1,
                            Value = "Datenschutzrecht"
                        },
                        new
                        {
                            Id = 121,
                            Description = "Öffentliches Recht",
                            FieldStatus = 1,
                            Value = "Öffentliches Recht"
                        },
                        new
                        {
                            Id = 122,
                            Description = "Essay",
                            FieldStatus = 1,
                            Value = "Essay"
                        },
                        new
                        {
                            Id = 123,
                            Description = "Case Study",
                            FieldStatus = 1,
                            Value = "Case Study"
                        });
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.HeadProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GHWId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GHWId");

                    b.HasIndex("ProjectId");

                    b.ToTable("HeadProposal");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.KindOfWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FieldStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KindOfWork");

                    b.HasData(
                        new
                        {
                            Id = 44,
                            Description = "Wissenschaftliches Paper",
                            FieldStatus = 1,
                            Value = "Wissenschaftliches Paper"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Hausarbeit",
                            FieldStatus = 1,
                            Value = "Hausarbeit"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Bachelorarbeit",
                            FieldStatus = 1,
                            Value = "Bachelorarbeit"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Diplomarbeit",
                            FieldStatus = 1,
                            Value = "Diplomarbeit"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Habilitation",
                            FieldStatus = 1,
                            Value = "Habilitation"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Habilitation",
                            FieldStatus = 1,
                            Value = "Habilitation"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Doktorarbeit",
                            FieldStatus = 1,
                            Value = "Doktorarbeit"
                        });
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BinaryDocumentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTimeSent")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsLogMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<int?>("SentByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BinaryDocumentId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SentByUserId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BinaryDocumentId")
                        .HasColumnType("integer");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatePlanned")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateRealised")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsFinalMilestone")
                        .HasColumnType("boolean");

                    b.Property<int>("MilestoneStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BinaryDocumentId");

                    b.HasIndex("BookingId");

                    b.ToTable("Milestone");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AuthorUsername")
                        .HasColumnType("text");

                    b.Property<string>("CustomerUsername")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DetailsLink")
                        .HasColumnType("text");

                    b.Property<int>("HeadProposalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectTopic")
                        .HasColumnType("text");

                    b.Property<int>("ProposalId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("BinaryData")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("text");

                    b.Property<string>("SeoFilename")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.PlagiarismCheckInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("AggregatedScore")
                        .HasColumnType("double precision");

                    b.Property<long>("Credits")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<long>("IdenticalWords")
                        .HasColumnType("bigint");

                    b.Property<long>("MinorChangedWords")
                        .HasColumnType("bigint");

                    b.Property<long>("RelatedMeaningWords")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<long>("TotalExcluded")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalWordsScanned")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("PlagiarismCheckInformation");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("CalculatedServiceCharges")
                        .HasColumnType("numeric");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("KindOfWorkId")
                        .HasColumnType("integer");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MaxBudget")
                        .HasColumnType("numeric");

                    b.Property<int?>("MinimumDegreeId")
                        .HasColumnType("integer");

                    b.Property<int>("PagesNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlannedBudget")
                        .HasColumnType("numeric");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectTopic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("KindOfWorkId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MinimumDegreeId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ChildProposalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("FinancialOffer")
                        .HasColumnType("numeric");

                    b.Property<int?>("HeadProposalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MilestonesCnt")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentProposalId")
                        .HasColumnType("integer");

                    b.Property<string>("PersonalMessage")
                        .HasColumnType("text");

                    b.Property<int>("ProposalType")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceCharges")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ChildProposalId")
                        .IsUnique();

                    b.HasIndex("HeadProposalId");

                    b.ToTable("Proposal");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ProposalStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.ToTable("ProposalStatusHistory");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("RateWriter")
                        .HasColumnType("integer");

                    b.Property<int>("StarRating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ServiceCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("ChargeAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("boolean");

                    b.Property<int?>("ServiceChargeTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceChargeTypeId");

                    b.ToTable("ServiceCharge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChargeAmount = 19m,
                            IsDefault = true,
                            IsPercentage = true,
                            StartDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChargeAmount = 9m,
                            EndDate = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            IsPercentage = false,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ServiceChargeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceChargeType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Default Service Charge",
                            Name = "Default Service Charge"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Service Charge",
                            Name = "Service Charge"
                        });
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethodNonce")
                        .HasColumnType("text");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("TransactionMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.UserRoleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal?>("AvgPricePerPage")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("DirectBooking")
                        .HasColumnType("boolean");

                    b.Property<int?>("HighestDegreeId")
                        .HasColumnType("integer");

                    b.Property<string>("IBAN")
                        .HasColumnType("text");

                    b.Property<int>("JobsPostedCnt")
                        .HasColumnType("integer");

                    b.Property<int>("PagesPerDay")
                        .HasColumnType("integer");

                    b.Property<bool>("PaymentVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PaypalEmail")
                        .HasColumnType("text");

                    b.Property<string>("PaypalPayerID")
                        .HasColumnType("text");

                    b.Property<int?>("PictureId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerPage")
                        .HasColumnType("numeric");

                    b.Property<string>("ProfileIntroduction")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HighestDegreeId");

                    b.HasIndex("PictureId");

                    b.ToTable("UserRoleData");
                });

            modelBuilder.Entity("KindOfWorkUserRoleData", b =>
                {
                    b.Property<int>("KindOfWorksId")
                        .HasColumnType("integer");

                    b.Property<int>("UserRoleDatasId")
                        .HasColumnType("integer");

                    b.HasKey("KindOfWorksId", "UserRoleDatasId");

                    b.HasIndex("UserRoleDatasId");

                    b.ToTable("KindOfWorkUserRoleData");
                });

            modelBuilder.Entity("LanguageUserRoleData", b =>
                {
                    b.Property<int>("LanguagesId")
                        .HasColumnType("integer");

                    b.Property<int>("UserRoleDatasId")
                        .HasColumnType("integer");

                    b.HasKey("LanguagesId", "UserRoleDatasId");

                    b.HasIndex("UserRoleDatasId");

                    b.ToTable("LanguageUserRoleData");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ProjectServiceCharge", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceChargesId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectsId", "ServiceChargesId");

                    b.HasIndex("ServiceChargesId");

                    b.ToTable("ProjectServiceCharge");
                });

            modelBuilder.Entity("BuzzwordProject", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Buzzword", null)
                        .WithMany()
                        .HasForeignKey("BuzzwordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuzzwordUserRoleData", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Buzzword", null)
                        .WithMany()
                        .HasForeignKey("BuzzwordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.UserRoleData", null)
                        .WithMany()
                        .HasForeignKey("UserRoleDatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertiseAreaProject", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ExpertiseArea", null)
                        .WithMany()
                        .HasForeignKey("ExpertiseAreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertiseAreaUserRoleData", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ExpertiseArea", null)
                        .WithMany()
                        .HasForeignKey("ExpertiseAreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.UserRoleData", null)
                        .WithMany()
                        .HasForeignKey("UserRoleDatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ApplicationRole", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.UserRoleData", "UserRoleData")
                        .WithOne("ApplicationUserRole")
                        .HasForeignKey("GhostWriter.Domain.Entities.ApplicationUserRole", "UserRoleDataId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("UserRoleData");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Booking", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.HeadProposal", "HeadProposal")
                        .WithMany()
                        .HasForeignKey("HeadProposalId");

                    b.Navigation("HeadProposal");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingStatusHistories")
                        .HasForeignKey("BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Document", "BinaryDocument")
                        .WithMany()
                        .HasForeignKey("BinaryDocumentId");

                    b.HasOne("GhostWriter.Domain.Entities.HeadProposal", "HeadProposal")
                        .WithOne("Conversation")
                        .HasForeignKey("GhostWriter.Domain.Entities.Conversation", "HeadProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinaryDocument");

                    b.Navigation("HeadProposal");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Dispute", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Booking", "Booking")
                        .WithMany("Disputes")
                        .HasForeignKey("BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Document", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Booking", "Booking")
                        .WithMany("Documents")
                        .HasForeignKey("BookingId");

                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", "UploadedByUser")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedByUserId");

                    b.Navigation("Booking");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.HeadProposal", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", "Ghostwriter")
                        .WithMany("Proposals")
                        .HasForeignKey("GHWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Ghostwriter");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Message", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Document", "BinaryDocument")
                        .WithMany()
                        .HasForeignKey("BinaryDocumentId");

                    b.HasOne("GhostWriter.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId");

                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", "SentByUser")
                        .WithMany()
                        .HasForeignKey("SentByUserId");

                    b.Navigation("BinaryDocument");

                    b.Navigation("Conversation");

                    b.Navigation("SentByUser");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Milestone", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Document", "BinaryDocument")
                        .WithMany()
                        .HasForeignKey("BinaryDocumentId");

                    b.HasOne("GhostWriter.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.Navigation("BinaryDocument");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Notification", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.PlagiarismCheckInformation", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Document", "Document")
                        .WithMany("PlagiarismCheckInformation")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Project", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.KindOfWork", "KindOfWork")
                        .WithMany("Projects")
                        .HasForeignKey("KindOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("GhostWriter.Domain.Entities.Degree", "MinimumDegree")
                        .WithMany()
                        .HasForeignKey("MinimumDegreeId");

                    b.Navigation("Customer");

                    b.Navigation("KindOfWork");

                    b.Navigation("Language");

                    b.Navigation("MinimumDegree");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Proposal", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Proposal", "ChildProposal")
                        .WithOne("ParentProposal")
                        .HasForeignKey("GhostWriter.Domain.Entities.Proposal", "ChildProposalId");

                    b.HasOne("GhostWriter.Domain.Entities.HeadProposal", "HeadProposal")
                        .WithMany()
                        .HasForeignKey("HeadProposalId");

                    b.Navigation("ChildProposal");

                    b.Navigation("HeadProposal");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ProposalStatusHistory", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Proposal", "Proposal")
                        .WithMany("ProposalStatuses")
                        .HasForeignKey("ProposalId");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Rate", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ServiceCharge", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ServiceChargeType", "ServiceChargeType")
                        .WithMany()
                        .HasForeignKey("ServiceChargeTypeId");

                    b.Navigation("ServiceChargeType");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Booking", "Booking")
                        .WithMany("Transactions")
                        .HasForeignKey("BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.UserRoleData", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Degree", "HighestDegree")
                        .WithMany()
                        .HasForeignKey("HighestDegreeId");

                    b.HasOne("GhostWriter.Domain.Entities.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId");

                    b.Navigation("HighestDegree");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("KindOfWorkUserRoleData", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.KindOfWork", null)
                        .WithMany()
                        .HasForeignKey("KindOfWorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.UserRoleData", null)
                        .WithMany()
                        .HasForeignKey("UserRoleDatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageUserRoleData", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.UserRoleData", null)
                        .WithMany()
                        .HasForeignKey("UserRoleDatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectServiceCharge", b =>
                {
                    b.HasOne("GhostWriter.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostWriter.Domain.Entities.ServiceCharge", null)
                        .WithMany()
                        .HasForeignKey("ServiceChargesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Projects");

                    b.Navigation("Proposals");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingStatusHistories");

                    b.Navigation("Disputes");

                    b.Navigation("Documents");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Document", b =>
                {
                    b.Navigation("PlagiarismCheckInformation");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.HeadProposal", b =>
                {
                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.KindOfWork", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.Proposal", b =>
                {
                    b.Navigation("ParentProposal");

                    b.Navigation("ProposalStatuses");
                });

            modelBuilder.Entity("GhostWriter.Domain.Entities.UserRoleData", b =>
                {
                    b.Navigation("ApplicationUserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
